steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'kms'
      - 'decrypt'
      - '--ciphertext-file=wind-alerts-staging.json.enc'
      - '--plaintext-file=wind-alerts-staging.json'
      - '--location=global'
      - '--keyring=alerts'
      - '--key=staging'
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['-q', 'compile', 'com.google.cloud.tools:jib-maven-plugin:1.5.1:build']
    env:
      - 'PROJECT_ID=wind-alerts-staging'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'wind-alerts', '--image', 'gcr.io/wind-alerts-staging/wind-alerts:1.0-SNAPSHOT', '--region', 'us-central1','--platform', 'managed', '--quiet', '--memory', '512Mi']