steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'kms'
      - 'decrypt'
      - '--ciphertext-file=wind-alerts-staging.json.enc'
      - '--plaintext-file=wind-alerts-staging.json'
      - '--location=global'
      - '--keyring=alerts'
      - '--key=staging'
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['-q', '-Duser.home=/builder/home', 'compile', 'jib:build']
    env:
      - 'PROJECT_ID=wind-alerts-staging'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'status', '--image', 'gcr.io/wind-alerts-staging/status', '--region', 'us-central1','--platform', 'managed', '--quiet', '--memory', '512Mi']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'alerts', '--image', 'gcr.io/wind-alerts-staging/alerts', '--region', 'us-central1','--platform', 'managed', '--quiet', '--memory', '512Mi']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'users', '--image', 'gcr.io/wind-alerts-staging/users', '--region', 'us-central1','--platform', 'managed', '--quiet', '--memory', '512Mi']
