steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'kms'
      - 'decrypt'
      - '--ciphertext-file=src/main/resources/wind-alerts-staging.json.enc'
      - '--plaintext-file=src/main/resources/wind-alerts-staging.json'
      - '--location=global'
      - '--keyring=alerts'
      - '--key=staging'
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['-q', 'compile', '-P', 'status', 'jib:build']
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['-q', 'compile', '-P', 'notifications', 'jib:build']
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['-q', 'compile', '-P', 'alerts', 'jib:build']
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['-q', 'compile', '-P', 'users', 'jib:build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'wind-alerts-alerts', '--image', 'gcr.io/wind-alerts-staging/wind-alerts-alerts:1.0-SNAPSHOT', '--region', 'asia-northeast1','--platform', 'managed', '--quiet', '--memory', '512Mi']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'wind-alerts-status', '--image', 'gcr.io/wind-alerts-staging/wind-alerts-status:1.0-SNAPSHOT', '--region', 'asia-northeast1','--platform', 'managed', '--quiet', '--memory', '512Mi']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'wind-alerts-notifications', '--image', 'gcr.io/wind-alerts-staging/wind-alerts-send-notifications:1.0-SNAPSHOT', '--region', 'asia-northeast1','--platform', 'managed', '--quiet', '--memory', '512Mi']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'wind-alerts-users', '--image', 'gcr.io/wind-alerts-staging/wind-alerts-users:1.0-SNAPSHOT', '--region', 'asia-northeast1','--platform', 'managed', '--quiet', '--memory', '512Mi']