steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['-q', 'clean', 'install']
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['-q', '-pl', 'status', 'com.google.cloud.tools:jib-maven-plugin:1.5.1:dockerBuild']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'status', 'gcr.io/wind-alerts-staging/status']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/wind-alerts-staging/status']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'status', '--image', 'gcr.io/wind-alerts-staging/status', '--region', 'us-central1','--platform', 'managed', '--quiet', '--memory', '512Mi']
